/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practical.pkg2;

import javax.swing.JOptionPane;

/**
 *
 * @author salaam
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sixInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tenInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sixInfo = new javax.swing.JLabel();
        tenInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practical 2");

        jLabel1.setText("Enter 6 digits:");

        jLabel2.setText("Edit 10 digits:");

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(sixInput, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(tenInput))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenInfo)
                            .addComponent(sixInfo))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(sixInfo))
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(tenInfo))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String text = sixInput.getText();
            int len = text.length();
            if(len == 6){
                int[] digits = new int[6];
                for(int i = 0; i < len; i++){
                    int n = Integer.parseInt(text.substring(i, i+1));
                    digits[i] = n;                
                }
                int d7, d8, d9, d10;
                 d7 = (4*digits[0] + 10*digits[1] + 9*digits[2] + 2*digits[3] + digits[4] + 7*digits[5] ) % 11;
                 d8 = (7*digits[0] + 8*digits[1] + 7*digits[2] + digits[3] + 9*digits[4] + 6*digits[5] ) % 11;
                 d9 = (9*digits[0] + digits[1] + 7*digits[2] + 8*digits[3] + 7*digits[4] + 7*digits[5] ) % 11;
                 d10 = (digits[0] + 2*digits[1] + 9*digits[2] + 10*digits[3] + 4*digits[4] + digits[5] ) % 11;
                 if(d7 == 10 || d8 == 10 || d9 == 10 || d10 == 10){
                     JOptionPane.showMessageDialog(null, "Unusable Number");
                 } else {
                     String checkDigits = String.valueOf(d7);
                     checkDigits += String.valueOf(d8);
                     checkDigits += String.valueOf(d9);
                     checkDigits += String.valueOf(d10);
                     
                     sixInfo.setText(checkDigits);
                 }
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String text = tenInput.getText();
            int len = text.length();
            if(len == 10){
                int[] digits = new int[10];
                for(int i = 0; i < 10; i++){
                    int num = Integer.parseInt(text.substring(i, i+1));
                    digits[i] = num;
                }
                int s1,s2,s3,s4;
                s1 = (digits[0] + digits[1] + digits[2] + digits[3] + digits[4] + digits[5] + digits[6] + digits[7] + digits[8] + digits[9]) % 11;
                s2 = (digits[0] + (2*digits[1]) + (3*digits[2]) + (4*digits[3]) + (5*digits[4]) + (6*digits[5]) + (7*digits[6]) + (8*digits[7]) + (9*digits[8]) + (10*digits[9])) % 11;
                s3 = (digits[0] + (4*digits[1]) + (9*digits[2]) + (5*digits[3]) + (3*digits[4]) + (3*digits[5]) + (5*digits[6]) + (9*digits[7]) + (4*digits[8]) + (digits[9])) % 11;
                s4 = (digits[0] + (8*digits[1]) + (5*digits[2]) + (9*digits[3]) + (4*digits[4]) + (7*digits[5]) + (2*digits[6]) + (6*digits[7]) + (3*digits[8]) + (10*digits[9])) % 11;
                
                if(s1 > 9 || s2 > 9 || s3 > 9 || s4 > 9){
                    JOptionPane.showMessageDialog(null, "Unusable");
                } else {
                    tenInfo.setText(s1 +"" + s2 +""+ s3 + "" + s4);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Enter 10 digits");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel sixInfo;
    private javax.swing.JTextField sixInput;
    private javax.swing.JLabel tenInfo;
    private javax.swing.JTextField tenInput;
    // End of variables declaration//GEN-END:variables
}
